# Generated by Django 5.1.5 on 2025-02-06 05:49

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('trade_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Trade name')),
                ('description', models.CharField(blank=True, null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('model', models.CharField(max_length=80, verbose_name='Model')),
                ('brands', models.CharField(max_length=100, verbose_name='Brands')),
                ('processor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Processor')),
                ('screen_size', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Screen size')),
                ('height', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Height')),
                ('width', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Width')),
                ('country_origin', models.CharField(max_length=60, verbose_name='Country of origin')),
                ('accessories', models.CharField(max_length=400, verbose_name='Accessories')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('img', cloudinary.models.CloudinaryField(max_length=255, verbose_name='img')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.category')),
            ],
        ),
    ]
